---
title: "Descriptive Report"
author: "William Murrah"
date: "4/9/2021"
output:
  html_document: default
  word_document: default
  pdf_document: default
bibliography: descriptiveReport.bib
csl: ../../style/apa.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(psych)
library(texreg)
```

The purpose of this project is to demonstrate the use of Rmarkdown to generate reports integrating text and R code with output [@Xie2018Rmarkdowndefinitive].

```{r}
source("code/cleanGSS2018.R")

summary(gss)
```

## Explore Distributions

@Tukey1977Exploratorydataanalysis said exploring data is really important.
```{r}
pairs.panels(gss[ , c("usetech", "happy", "rincome")])
```

```{r}
describe(gss[ , c("usetech", "happy", "rincome")])
```

```{r}
aggregate(rincome ~ race + sex, data = gss, 
          FUN = function(x) c(M = mean(x), SD = sd(x), n =  length(x)))
```
```{r}
library(tables)
M <- function(x) mean(x, na.rm = TRUE)
SD <- function(x) sd(x, na.rm = TRUE)
n <- function(x) round(length(x))
tabular((rincome)*(M + SD) + 1 ~ (race * sex) + 1, data = gss)
```

## Models

```{r}
mod0 <- lm(rincome ~ 1, data = gss)
mod1 <- lm(rincome ~ happy + usetech, data = gss)
mod1x <- lm(rincome ~ happy*usetech, data = gss)
```

```{r, results='asis'}
texreg(list(mod0, mod1, mod1x))
```

# References

